### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by 99Kies**
just Dockerfile, to Create a environment for python-sdk.

### CODE REVIEW

**Comment by JimmyShi22** [comment]
Good idea! It will take some time to check this before merging

**Comment by 99Kies** [comment]
ok, my friend, this dockerfile have one problem.

it is ,
**when i try to run (it's mean in docker build)**
`bash nodes/127.0.0.1/start_all.sh`
it will **failed.** but emm, **this dockerfile also can successful build.**
**The solution to the problem**
you need run it , when you run this images(docker run -it -p 20200:20200 --name python-sdk fisco-python-sdk)
`bash nodes/127.0.0.1/start_all.sh`
and than you can test it by 
`./console.py getNodeVersion`


poor english , soory 

> Good idea! It will take some time to check this before merging

**Comment by 99Kies** [comment]
ok, my friend, this dockerfile have one problem.

is ,
when i try to run (it's mean in docker build)
bash nodes/127.0.0.1/start_all.shit will failed. but emm, this dockerfile also can successful build. The solution to the problemyou need run it , when you run this images(docker run -it -p 20200:20200 --name python-sdk fisco-python-sdk)bash nodes/127.0.0.1/start_all.shand than you can test it by "./console.py getNodeVersion"

poor english , soory 




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jimmyshi"<notifications@github.com&gt;; 
发送时间: 2019年12月11日(星期三) 凌晨1:15
收件人: "FISCO-BCOS/python-sdk"<python-sdk@noreply.github.com&gt;; 
抄送: "1290017556"<1290017556@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [FISCO-BCOS/python-sdk] Dockerfile (#81)




Good idea! It will take some time to check this before merging

**Comment by JimmyShi22** [comment]
It's ok to go into container and start all nodes.

**Comment by 99Kies** [comment]
> 可以进入容器并启动所有节点。

yes, but you need give Enough ports for your docker container.
you can try it, help me to Perfect his😂

**Comment by JimmyShi22** [comment]
That's right. It's also a good thing to learn docker from your PR!

**Comment by 99Kies** [comment]
If this can be used. Can be placed in dockerhub actually, so more convenient 😂. I also very willing to help.

**Comment by cyjseagull** [comment]
> If this can be used. Can be placed in dockerhub actually, so more convenient 😂. I also very willing to help.

**Comment by cyjseagull** [comment]
How about add the Dockerfile into ci, too.

**Comment by 99Kies** [comment]
> How about add the Dockerfile into ci, too.

Refers to this?
[https://gitlab.com/gitlab-org/gitlab/issues/22801](https://gitlab.com/gitlab-org/gitlab/issues/22801)
maybe, you can try it . than you can submit PR😂

**Comment by JimmyShi22** [comment]
Hi! @99Kies 
I'm trying to start this image. where I can pull this image?
Maybe we can discuss in WeChat. (Connect me: @石翔 Jimmy Shi)

**Comment by 99Kies** [comment]
OK👌



发自我的&nbsp;iPad


------------------ Original ------------------

**Pull request merged**
